### PR TITLE
Avoiding segment violation when a cell is empty

### PR DESCRIPTION
**Pull request by FelipeMLopez**
Hello!
Some time ago I opened Issue #169 because I had a problem when I generated a cell without points.
Later I solved the problem, but I didn't comment on it. I recovered the solution after Diana's comment.
The problem is that RepairHeader() does not check for points before performing operations. I simply added a check to prevent from doing something if there are no points.

### CODE REVIEW

**Comment by mloskot** [comment]
Hmm, did you intentionally submit this PR against your own fork?
Perhaps you aimed to submit it against the upstream at https://github.com/libLAS/libLAS/

**Comment by FelipeMLopez** [comment]
Hi @mloskot 
I wanted to submit it against the upstream, sorry.
Could you change it or should I do a new PR?
Thanks.

**Comment by mloskot** [comment]
I can not re-direct it.
I'd appreciate if you could re-submit it as a new PR for libLAS repo.

**Comment by FelipeMLopez** [comment]
No problem!
I close this PR.

**Pull request closed without merging**
